### ISSUE TITLE
Import hospital data

### ISSUE THREAD

**Issue by fmarani** [HospitalAid/hospitalaid#1]
We need to keep an official list of hospitals in our backend. This will be used to complement hospital information that we collect from our users directly. These will be stored in a separate database table.

We are most of all interested in GPS coordinates, so we can place these on a map.

Possible sources of data:
- https://healthsites.io/
- https://wiki.openstreetmap.org/wiki/Global_Healthsites_Mapping_Project
- https://data.humdata.org/organization/healthsites?q=&ext_page_size=100
- https://data.humdata.org/dataset/09f9a766-d24c-4376-b923-726bede4059d/resource/d893d18c-d68e-4fce-a092-7f81225df9cd/download/brazil.csv

We need to make sure these are inlcuded
http://portal.saude.pe.gov.br/hospitais

**Comment by cmontemuino** [comment]
What's the scope of this task:
* collecting the hospital addresses (along with GPS coordinates) into a mardkown file?
* entering the data into a table?, in such a case, do we have a design/db available?

**Comment by fmarani** [comment]
The outcome of this ticket needs to be:
- a dedicated Django model to represent the remote source of data. 
- an importer that connects to the source and imports the hospitals that we are targeting for a first release (see last link) in the new Django model table

The database design can be driven by whatever the remote source is returning, as long as it contains name and GPS coordinates.

**Comment by jeff303** [comment]
I was experimenting with Healthsites, and right away hit an issue: healthsites/healthsites#1411

However, it seems possible to work around it anyway.  And in spite of what the documentation says, an API key doesn't even seem to be required to execute the queries (though we can always create one if required; I already created a personal one).  Sample Python code here:

```
import requests
searchTerm = "Rush University"
searchResponse = requests.get(f"https://healthsites.io/api/v2/facilities/autocomplete/?q={searchTerm}")
searchResponse.json()
[{'label': 'Rush University Medical Center', 'id': 'way/239001073'}]
facilityId = searchResponse.json()[0]['id']
facilityId
'way/239001073'
facilityResponse = requests.get(f"https://healthsites.io/api/v2/facilities/{facilityId}")
facilityResponse.json()
{'attributes': {'addr_city': 'Chicago', 'wheelchair': 'yes', 'amenity': 'hospital', 'name': 'Rush University Medical Center', 'emergency': 'yes', 'changeset_user': 'Zol87', 'opening_hours': '24/7', 'changeset_id': 81881325, 'changeset_timestamp': '2020-03-06T18:48:22', 'addr_postcode': '60612', 'addr_housenumber': '1653', 'changeset_version': 5, 'addr_street': 'West Congress Parkway', 'uuid': '48c8d03da8fe4aad8156d726a391bafa'}, 'centroid': {'type': 'Point', 'coordinates': [-87.66896905776822, 41.87345725267924]}, 'osm_id': 239001073, 'osm_type': 'way', 'completeness': 31.0}
```

@fmarani , does this answer the question of how the API coordinates would be represented?  I checked out the humdata.org site as well, and their data appears to be represented in the same structure (I think Shapefile).  In any event, we can always transform this however is needed.

**Comment by fmarani** [comment]
From a first look, we would need the fields: name, city, addr_* and coordinates

Next steps:
- creating a copy of main/models/main.py::Hospital called HealthSitesHospital, which the fields that we want to import
- integrate the code above in a Django management command (see file main/management/commands/command.py) along with a bit of extra code that writes to the new model

**Comment by jeff303** [comment]
@fmarani , it seems that management commands simply have input args, and aren't really a REPL, correct?  So, should we expect people to already know the facilityId and pass it into this command?  Or should we actually have a command that runs the search and prints out results to stdout, to help people find the facilityId they want?

**Comment by fmarani** [comment]
Correct, they are not REPL. They are just unix commands which take arguments from the command line.

We could use the search endpoint to do a search with a country passed in as input arg and then cycle through all facilities to download the data to the db.

**Comment by jeff303** [comment]
Opened #7 .  Let me know if this approach looks correct.  (There's still some Python/Django stuff I'm rusty on).

**Comment by fmarani** [comment]
Looks good. I added a few commits but had to reopen the PR on the repo - #8
