### ISSUE TITLE
Request is not updated when hospital name changes

### ISSUE THREAD

**Issue by VictorMirandaEE** [HospitalAid/hospitalaid#39]
If the hospital name changes, the old requests remain attached to the old hospital name.

**Comment by fmarani** [comment]
This happens because we are trying to manage hospitals as independent entities from the user, so multiple users can manage one hospital. This may be something that we do not need at this stage?

**Comment by fmarani** [comment]
I fixed the number of hospitals per user to 1 as it simplifies the registration/update profile steps. Can change later if needed.
